services:
  api:
    build: .
    container_name: crown-card-api
    ports:
      - "3000:3000"
    environment:
      # App
      PORT: 3000
      ROOTPATH: /usr/src/app
      AUTH_TOKEN: ${AUTH_TOKEN}
      ADMIN_AUTH_TOKEN: ${ADMIN_AUTH_TOKEN}
      # DB
      DB_HOST: postgres
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  postgres:
    image: postgres:15-alpine
    container_name: crown-card-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost" ]
      interval: 2s
      timeout: 5s
      retries: 20

volumes:
  db-data:
